name: alltimeQB
favicon: null
layout_spectrum: 0.217342
typography_spectrum: 0.674549
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#e3c785'
    - '#565759'
    - '#0d0702'
    - '#3a2918'
  brandStrength: 0.75
  lightness: 0.885135
  saturation: 0.34572
  rhythmicContrast: 0.643018
purpose:
  - name: null
    item: null
    url: null
