name: alltimeQB
favicon: null
layout_spectrum: 0.33055
typography_spectrum: 0.674549
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: UA-5103660-9
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors: []
  brandStrength: 0.5
  lightness: 0.439189
  saturation: 0.34572
  rhythmicContrast: 0.643018
purpose:
  - name: null
    item: null
    url: null
